In [4]:
import pandas as pd

In [5]:
#Series 1-D data

Series = pd.Series([1, 2,3,4,5])

In [6]:
type(Series)

pandas.core.series.Series

In [8]:
#2-D dataframe
frame = pd.DataFrame([{
    'name': 'tea',
    'price': 20
}, {
    'name': 'coffee',
    'price': 25
}])

In [9]:
type(frame)

pandas.core.frame.DataFrame

In [11]:
frame.to_csv('items.csv', header=True, index=False)

In [13]:
catalog_df = pd.read_csv('catalog.csv')

In [14]:
catalog_df

,Item_ID,Category,Dish_Name,Description,Price (INR),Vegetarian (Y/N),Spice_Level (1-5)
0,APP001,Appetizers,Samosa Chaat,"Crushed samosas topped with yogurt, tamarind a...",250,Y,2
1,APP002,Appetizers,Chicken Tikka,Boneless chicken pieces marinated in yogurt an...,380,N,3
2,APP003,Appetizers,Paneer Pakora,Indian cheese fritters seasoned and deep-fried...,300,Y,1
3,MC_01,Main Course (Chicken),Butter Chicken (Murgh Makhani),Tandoor-cooked chicken simmered in a rich toma...,550,N,2
4,MC_02,Main Course (Chicken),Chicken Korma,"Chicken pieces in a creamy, mild sauce made wi...",580,N,1
5,MC_03,Main Course (Lamb),Lamb Rogan Josh,A signature Kashmiri lamb curry cooked in a gr...,650,N,3
6,MC_04,Main Course (Vegetarian),Palak Paneer,Fresh spinach puree cooked with chunks of Indi...,480,Y,2
7,MC_05,Main Course (Vegetarian),Dal Makhani,Black lentils and kidney beans slow-cooked wit...,420,Y,1
8,BRD001,Breads,Butter Naan,"Soft flatbread cooked in a tandoor, brushed wi...",80,Y,1
9,BRD002,Breads,Garlic Naan,Soft flatbread infused with garlic and cilantro.,90,Y,1
10,RCE001,Rice & Biryani,Vegetable Biryani,"Basmati rice layered with mixed vegetables, he...",450,Y,2
11,DES001,Desserts,Gulab Jamun,Deep-fried milk solids (khoya) dumplings soake...,150,Y,1
12,BEV001,Beverages,Mango Lassi,A sweet and creamy drink made from yogurt and ...,180,Y,1

In [15]:

catalog_df['Item_ID'] == 'BRD001	'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
Name: Item_ID, dtype: bool

In [19]:
catalog_df

,Item_ID,Category,Dish_Name,Description,Price (INR),Vegetarian (Y/N),Spice_Level (1-5)
0,APP001,Appetizers,Samosa Chaat,"Crushed samosas topped with yogurt, tamarind a...",250,Y,2
1,APP002,Appetizers,Chicken Tikka,Boneless chicken pieces marinated in yogurt an...,380,N,3
2,APP003,Appetizers,Paneer Pakora,Indian cheese fritters seasoned and deep-fried...,300,Y,1
3,MC_01,Main Course (Chicken),Butter Chicken (Murgh Makhani),Tandoor-cooked chicken simmered in a rich toma...,550,N,2
4,MC_02,Main Course (Chicken),Chicken Korma,"Chicken pieces in a creamy, mild sauce made wi...",580,N,1
5,MC_03,Main Course (Lamb),Lamb Rogan Josh,A signature Kashmiri lamb curry cooked in a gr...,650,N,3
6,MC_04,Main Course (Vegetarian),Palak Paneer,Fresh spinach puree cooked with chunks of Indi...,480,Y,2
7,MC_05,Main Course (Vegetarian),Dal Makhani,Black lentils and kidney beans slow-cooked wit...,420,Y,1
8,BRD001,Breads,Butter Naan,"Soft flatbread cooked in a tandoor, brushed wi...",80,Y,1
9,BRD002,Breads,Garlic Naan,Soft flatbread infused with garlic and cilantro.,90,Y,1
10,RCE001,Rice & Biryani,Vegetable Biryani,"Basmati rice layered with mixed vegetables, he...",450,Y,2
11,DES001,Desserts,Gulab Jamun,Deep-fried milk solids (khoya) dumplings soake...,150,Y,1
12,BEV001,Beverages,Mango Lassi,A sweet and creamy drink made from yogurt and ...,180,Y,1

In [23]:
catalog_df = pd.read_csv('catalog.csv')

In [21]:
catalog_df

,Item_ID,Category,Dish_Name,Description,Price,Vegetarian,Spice_Level
0,APP001,Appetizers,Samosa Chaat,"Crushed samosas topped with yogurt, tamarind a...",250,Y,2
1,APP002,Appetizers,Chicken Tikka,Boneless chicken pieces marinated in yogurt an...,380,N,3
2,APP003,Appetizers,Paneer Pakora,Indian cheese fritters seasoned and deep-fried...,300,Y,1
3,MC_01,Main Course (Chicken),Butter Chicken (Murgh Makhani),Tandoor-cooked chicken simmered in a rich toma...,550,N,2
4,MC_02,Main Course (Chicken),Chicken Korma,"Chicken pieces in a creamy, mild sauce made wi...",580,N,1
5,MC_03,Main Course (Lamb),Lamb Rogan Josh,A signature Kashmiri lamb curry cooked in a gr...,650,N,3
6,MC_04,Main Course (Vegetarian),Palak Paneer,Fresh spinach puree cooked with chunks of Indi...,480,Y,2
7,MC_05,Main Course (Vegetarian),Dal Makhani,Black lentils and kidney beans slow-cooked wit...,420,Y,1
8,BRD001,Breads,Butter Naan,"Soft flatbread cooked in a tandoor, brushed wi...",80,Y,1
9,BRD002,Breads,Garlic Naan,Soft flatbread infused with garlic and cilantro.,90,Y,1
10,RCE001,Rice & Biryani,Vegetable Biryani,"Basmati rice layered with mixed vegetables, he...",450,Y,2
11,DES001,Desserts,Gulab Jamun,Deep-fried milk solids (khoya) dumplings soake...,150,Y,1
12,BEV001,Beverages,Mango Lassi,A sweet and creamy drink made from yogurt and ...,180,Y,1

In [54]:
catalog_df = pd.read_csv('catalog.csv')

In [55]:
catalog_df

,ItemID,ItemName,RestaurantName,Price,Description
0,I001,Kung Pao Chicken,Golden Dragon,12.99,Spicy stir fried chicken with peanuts and chili
1,I002,Beef Tacos,El Toro Loco,9.49,Soft tortillas filled with seasoned beef and s...
2,I003,Pad Thai,Spice Route,11.99,Classic rice noodle dish with tofu and peanuts
3,I004,Greek Salad,The Greek Table,8.99,Fresh salad with feta olives and olive oil
4,I005,Margherita Pizza,Bella Vita,13.49,Wood fired pizza with tomato sauce and mozzarella
5,I006,Sweet and Sour Pork,Dragon Wok,10.99,Crispy pork in tangy sweet and sour sauce
6,I007,Chicken Shawarma,La Casa De Tapas,12.49,Grilled chicken wrapped with garlic sauce
7,I008,Chicken Quesadilla,Chili Lime,9.99,Grilled tortilla stuffed with cheese and chicken
8,I009,Spaghetti Carbonara,Pasta Palace,12.99,Classic pasta with eggs cheese and bacon
9,I010,Green Curry,Phuket Spice,11.49,Thai curry with coconut milk and vegetables
10,I011,Spring Rolls,Shanghai Express,6.99,Crispy rolls filled with vegetables
11,I012,Enchiladas,La Fiesta,10.99,Tortillas rolled with chicken and mild chili s...
12,I013,Hummus Plate,Olive Grove,7.99,Mashed chickpeas served with pita bread
13,I014,Lasagna,Trattoria Roma,13.99,Layered pasta with meat sauce and cheese
14,I015,Basil Fried Rice,Lotus Leaf,10.49,Thai style fried rice with basil and egg

In [56]:
catalog_df.Price

0     12.99
1      9.49
2     11.99
3      8.99
4     13.49
5     10.99
6     12.49
7      9.99
8     12.99
9     11.49
10     6.99
11    10.99
12     7.99
13    13.99
14    10.49
Name: Price, dtype: float64

In [57]:
catalog_df['ItemID'] == 'I015'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
Name: ItemID, dtype: bool

In [58]:
catalog_df.iloc[0]

ItemID                                                       I001
ItemName                                         Kung Pao Chicken
RestaurantName                                      Golden Dragon
Price                                                       12.99
Description       Spicy stir fried chicken with peanuts and chili
Name: 0, dtype: object

In [59]:
catalog_df.loc[1]

ItemID                                                         I002
ItemName                                                 Beef Tacos
RestaurantName                                         El Toro Loco
Price                                                          9.49
Description       Soft tortillas filled with seasoned beef and s...
Name: 1, dtype: object

In [60]:
catalog_df = pd.read_csv('catalog.csv')

In [61]:
catalog_df

,ItemID,ItemName,RestaurantName,Price,Description
0,I001,Kung Pao Chicken,Golden Dragon,12.99,Spicy stir fried chicken with peanuts and chili
1,I002,Beef Tacos,El Toro Loco,9.49,Soft tortillas filled with seasoned beef and s...
2,I003,Pad Thai,Spice Route,11.99,Classic rice noodle dish with tofu and peanuts
3,I004,Greek Salad,The Greek Table,8.99,Fresh salad with feta olives and olive oil
4,I005,Margherita Pizza,Bella Vita,13.49,Wood fired pizza with tomato sauce and mozzarella
5,I006,Sweet and Sour Pork,Dragon Wok,10.99,Crispy pork in tangy sweet and sour sauce
6,I007,Chicken Shawarma,La Casa De Tapas,12.49,Grilled chicken wrapped with garlic sauce
7,I008,Chicken Quesadilla,Chili Lime,9.99,Grilled tortilla stuffed with cheese and chicken
8,I009,Spaghetti Carbonara,Pasta Palace,12.99,Classic pasta with eggs cheese and bacon
9,I010,Green Curry,Phuket Spice,11.49,Thai curry with coconut milk and vegetables
10,I011,Spring Rolls,Shanghai Express,6.99,Crispy rolls filled with vegetables
11,I012,Enchiladas,La Fiesta,10.99,Tortillas rolled with chicken and mild chili s...
12,I013,Hummus Plate,Olive Grove,7.99,Mashed chickpeas served with pita bread
13,I014,Lasagna,Trattoria Roma,13.99,Layered pasta with meat sauce and cheese
14,I015,Basil Fried Rice,Lotus Leaf,10.49,Thai style fried rice with basil and egg

In [62]:
catalog_df = catalog_df.set_index('ItemID')

In [63]:
print(catalog_df)

                   ItemName    RestaurantName  Price  \
ItemID
I001       Kung Pao Chicken     Golden Dragon  12.99
I002             Beef Tacos      El Toro Loco   9.49
I003               Pad Thai       Spice Route  11.99
I004            Greek Salad   The Greek Table   8.99
I005       Margherita Pizza        Bella Vita  13.49
I006    Sweet and Sour Pork        Dragon Wok  10.99
I007       Chicken Shawarma  La Casa De Tapas  12.49
I008     Chicken Quesadilla        Chili Lime   9.99
I009    Spaghetti Carbonara      Pasta Palace  12.99
I010            Green Curry      Phuket Spice  11.49
I011           Spring Rolls  Shanghai Express   6.99
I012             Enchiladas         La Fiesta  10.99
I013           Hummus Plate       Olive Grove   7.99
I014                Lasagna    Trattoria Roma  13.99
I015       Basil Fried Rice        Lotus Leaf  10.49

                                              Description
ItemID
I001      Spicy stir fried chicken with peanuts and chili
I002    Soft tortillas filled with seasoned beef and s...
I003       Classic rice noodle dish with tofu and peanuts
I004           Fresh salad with feta olives and olive oil
I005    Wood fired pizza with tomato sauce and mozzarella
I006            Crispy pork in tangy sweet and sour sauce
I007            Grilled chicken wrapped with garlic sauce
I008     Grilled tortilla stuffed with cheese and chicken
I009             Classic pasta with eggs cheese and bacon
I010          Thai curry with coconut milk and vegetables
I011                  Crispy rolls filled with vegetables
I012    Tortillas rolled with chicken and mild chili s...
I013              Mashed chickpeas served with pita bread
I014             Layered pasta with meat sauce and cheese
I015             Thai style fried rice with basil and egg

In [65]:
catalog_df.loc['I015']

ItemName                                  Basil Fried Rice
RestaurantName                                  Lotus Leaf
Price                                                10.49
Description       Thai style fried rice with basil and egg
Name: I015, dtype: object

In [68]:
catalog_df.loc['I015', 'RestaurantName']

'Lotus Leaf'

In [69]:
catalog_df.loc[:, 'ItemName']

ItemID
I001       Kung Pao Chicken
I002             Beef Tacos
I003               Pad Thai
I004            Greek Salad
I005       Margherita Pizza
I006    Sweet and Sour Pork
I007       Chicken Shawarma
I008     Chicken Quesadilla
I009    Spaghetti Carbonara
I010            Green Curry
I011           Spring Rolls
I012             Enchiladas
I013           Hummus Plate
I014                Lasagna
I015       Basil Fried Rice
Name: ItemName, dtype: object

In [70]:
catalog_df = pd.read_csv('catalog.csv', index_col = 'ItemID')

In [71]:
catalog_df.loc['I011']

ItemName                                 Spring Rolls
RestaurantName                       Shanghai Express
Price                                            6.99
Description       Crispy rolls filled with vegetables
Name: I011, dtype: object

In [72]:
catalog_df.loc['I011']['Price']

np.float64(6.99)

In [73]:
# how to search for records where price > $12

catalog_df.loc[catalog_df['Price']>12]

,ItemName,RestaurantName,Price,Description
ItemID,,,,
I001,Kung Pao Chicken,Golden Dragon,12.99,Spicy stir fried chicken with peanuts and chili
I005,Margherita Pizza,Bella Vita,13.49,Wood fired pizza with tomato sauce and mozzarella
I007,Chicken Shawarma,La Casa De Tapas,12.49,Grilled chicken wrapped with garlic sauce
I009,Spaghetti Carbonara,Pasta Palace,12.99,Classic pasta with eggs cheese and bacon
I014,Lasagna,Trattoria Roma,13.99,Layered pasta with meat sauce and cheese

In [74]:
#Increase prices by 15%
catalog_df['Price'] = catalog_df['Price'] * 1.15

In [75]:
catalog_df

,ItemName,RestaurantName,Price,Description
ItemID,,,,
I001,Kung Pao Chicken,Golden Dragon,14.9385,Spicy stir fried chicken with peanuts and chili
I002,Beef Tacos,El Toro Loco,10.9135,Soft tortillas filled with seasoned beef and s...
I003,Pad Thai,Spice Route,13.7885,Classic rice noodle dish with tofu and peanuts
I004,Greek Salad,The Greek Table,10.3385,Fresh salad with feta olives and olive oil
I005,Margherita Pizza,Bella Vita,15.5135,Wood fired pizza with tomato sauce and mozzarella
I006,Sweet and Sour Pork,Dragon Wok,12.6385,Crispy pork in tangy sweet and sour sauce
I007,Chicken Shawarma,La Casa De Tapas,14.3635,Grilled chicken wrapped with garlic sauce
I008,Chicken Quesadilla,Chili Lime,11.4885,Grilled tortilla stuffed with cheese and chicken
I009,Spaghetti Carbonara,Pasta Palace,14.9385,Classic pasta with eggs cheese and bacon
I010,Green Curry,Phuket Spice,13.2135,Thai curry with coconut milk and vegetables
I011,Spring Rolls,Shanghai Express,8.0385,Crispy rolls filled with vegetables
I012,Enchiladas,La Fiesta,12.6385,Tortillas rolled with chicken and mild chili s...
I013,Hummus Plate,Olive Grove,9.1885,Mashed chickpeas served with pita bread
I014,Lasagna,Trattoria Roma,16.0885,Layered pasta with meat sauce and cheese
I015,Basil Fried Rice,Lotus Leaf,12.0635,Thai style fried rice with basil and egg

In [76]:
catalog_df.to_csv('new_catalog.csv')